iotool:
  batch_size: 32
  shuffle: False
  num_workers: 1
  collate_fn: CollateSparse
  sampler:
    name: SequentialBatchSampler
  dataset:
    name: LArCVDataset
    limit_num_files: 10
    schema:
      input_data:
        - parse_sparse3d_scn
        - sparse3d_geant4
      segment_label:
        - parse_sparse3d_scn
        - sparse3d_geant4_semantics
model:
  name: uresnet_ppn_chain
  modules:
    ppn:
      num_strides: 6
      filters: 16
      num_classes: 5
      data_dim: 3
      downsample_ghost: False
      use_encoding: False
      ppn_num_conv: 1
      score_threshold: 0.5
      ppn1_size: 24
      ppn2_size: 96
      spatial_size: 768
    uresnet_lonely:
      freeze: False
      num_strides: 6
      filters: 16
      num_classes: 5
      data_dim: 3
      spatial_size: 24576
      ghost: False
      features: 1
  network_input:
    - input_data
trainval:
  seed: 123
  learning_rate: 0.001
  unwrapper: unwrap_3d_scn
  weight_prefix: weights/snapshot
  iterations: 1
  report_step: 1
  checkpoint_step: 100
  log_dir: log_inference
  train: False
  debug: True
