iotool:
  batch_size: 32
  shuffle: False
  num_workers: 1
  collate_fn: CollateSparse
  sampler:
    name: RandomSequenceSampler
#    name: SequentialBatchSampler  # use if you want to overtrain on a fixed sample (also set the batch size to the full sample size)
  dataset:
    name: LArCVDataset
    limit_num_files: 100
    schema:
      input_data:
        - parse_sparse3d_scn  # this parser takes one argument: the tree with EventSparseTensor3Ds
        - sparse3d_geant4     # this is the name of the tree
      segment_label:
        - parse_sparse3d_scn  # this parser takes one argument: the tree with particle labels
        - sparse3d_pcluster_semantics
      particles_label:
        - parse_particle_points  # this parser takes two arguments: the tree with EventSparseTensor3Ds and the one with the LArCV particles
        - cluster3d_pcluster
        - particle_pcluster_corrected
model:
  name: uresnet_ppn_chain
  modules:
    ppn:
      freeze: False
      num_strides: 7   # needs to match UResNet.  (allows PPN to understand its input)
      filters: 16      # ditto
      num_classes: 5   # ditto
      data_dim: 3      # ditto
      downsample_ghost: False
      use_encoding: False
      ppn_num_conv: 1
      score_threshold: 0.5
      ppn1_size: 24
      ppn2_size: 96
      spatial_size: 1920
    uresnet_lonely:
      freeze: False
      num_strides: 7    # (number of downsample layers) + 1
      filters: 16       # number of features generated at first layer, doubled (?) each layer
      num_classes: 5
      data_dim: 3
      spatial_size: 1920
      ghost: False      # artifacts from rebuilding 3D out of 2D views
      features: 1       # number of input features
  network_input:
    - input_data
    - particles_label
  loss_input:     # truth values for supervised learning.  (also from 'schema')
    - segment_label
    - particles_label
trainval:
  seed: 123
  learning_rate: 0.001
  unwrapper: unwrap_3d_scn
  weight_prefix: snapshot
  iterations: 15000
  report_step: 1
  checkpoint_step: 1000
  log_dir: log_train
  train: True
  debug: False
